### ISSUE TITLE
Is this still being used? 

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble-utils#5]
We should delete it otherwise

**Comment by jonschlinkert** [comment]
@doowb ping. should we delete this repo?

**Comment by doowb** [comment]
Probably... I thought I deprecated this on npm, but there's been downloads within the past month.
Is there a good way to point that to other repos? I think the functionality in this one is split between a couple different ones now.

The other option is to just wrap the other repos in this and keep it there so the npm stuff isn't broken.

**Comment by doowb** [comment]
Actually, searching on github shows that there are some projects using an older version of assemble and that's probably the reason for assemble-utils getting downloaded.

**Comment by jonschlinkert** [comment]
k, we'll try to keep this intact then

> Is there a good way to point that to other repos?

well, kind of. we can just start moving utils out of this lib and then have this lib require them, both in the pkg deps and then exporting them in the index.js file in the root. then eventually this project would just be a collection of external utils.

**Comment by doowb** [comment]
@jonschlinkert I'm going to use this repo for some of our new assemble stuff and remove all the existing code. I'll bump the minor so the older versions are still accessible if needed.

**Comment by doowb** [comment]
Created 0.2.0 for assemble 0.6.0+. Tagged as `beta` on npm right now.
